### ISSUE TITLE
forkJoin not completing when one of observables is loadFromDelayedObservable delayType = 'none'

### ISSUE THREAD

**Issue by jaybloke** [Nodonisko/ionic-cache#78] opened 2018-06-18 02:19 UTC
Not sure if this a bug or simply can't be achieved when subscribing to multiple cache observables with forkJoin.

Example:

```
plan(): Observable<any> {
  let request = this.http.get<any>(`${ENV.apiHost}/plan`).map(response => response.plan);
  return this.cache.loadFromObservable('plan', request, 'group', 60000);
}

services(): Observable<any> {
  let request = this.http.get<any>(`${ENV.apiHost}/services`).map(response => response.services);
  return this.cache.loadFromDelayedObservable('services', request, 'group', 60000, 'none');
}

Observable.forkJoin([this.plan(), this.services()]).subscribe(
  (results: any[]) => {
    console.log('Not called once services in cache');
  }
)
```

Basically, once services is in the cache, the call to forkJoin never completes.

**Comment by darthdie** [comment] 2018-06-18 03:04
Thanks. I believe I know what the issue is. I'll confirm a fix in the next day or so.

**Comment by jaybloke** [comment] 2018-06-18 03:06
Nice one @darthdie ! Highly appreciate your quick response 👍

**Comment by darthdie** [comment] 2018-06-18 14:51
Just published version 3.1.2 with a fix for this. Let me know if you have any more issues, thanks!

**Closed by darthdie** 2018-06-18 14:51 UTC

**Comment by jaybloke** [comment] 2018-06-18 23:53
Just tried the new version out and happy to say it works like a dream - Thanks @darthdie for fixing this so quickly!
